# Generated by Django 2.1.8 on 2019-06-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='video',
            name='song_band',
            field=models.CharField(max_length=30),
        ),
    ]
