# Generated by Django 2.1.8 on 2019-06-07 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190607_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-year_id', 'concert_id']},
        ),
    ]
