# Generated by Django 2.1.8 on 2019-06-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20190607_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-year_id', 'concert_id', 'team_id']},
        ),
    ]
