# Generated by Django 2.1.8 on 2019-06-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20190605_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
