# Generated by Django 2.1.8 on 2019-05-29 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0002_auto_20190529_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freehour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Freeweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freetimes.Freehour')),
                ('members', models.ManyToManyField(blank=True, related_name='member_freetimes', to='members.Member')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freetimes.Freeweek')),
            ],
        ),
    ]
