# Generated by Django 2.1.8 on 2019-05-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('part', models.CharField(max_length=5)),
                ('mudanNo', models.IntegerField()),
                ('univNo', models.IntegerField()),
                ('major', models.CharField(max_length=20)),
                ('alive', models.CharField(max_length=5)),
            ],
        ),
    ]
