# Generated by Django 2.1.8 on 2019-05-29 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MudanNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='UniveNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='alive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Alive'),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Major'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mudanNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.MudanNo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Part'),
        ),
        migrations.AlterField(
            model_name='member',
            name='univNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.UniveNo'),
        ),
    ]
