# Generated by Django 2.1.8 on 2019-06-05 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['part_id']},
        ),
    ]
