# Generated by Django 2.1.8 on 2019-06-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190606_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['mudanNo', 'part_id']},
        ),
    ]
