# Generated by Django 2.1.8 on 2019-06-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20190607_0612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['mudanNo_id', 'part_id']},
        ),
    ]
